#live server configurations
#######################################
#   RTMP configurations(stand-alone)  #
#######################################
[rtmp]
enabled = true
port = 1935
# optional:
# gop_num = 0
# max_no_data_retries = 10
# read_timeout_ms = 2000

########################################
# HTTPFLV configurations               #
########################################
[httpflv]
enabled = true
port = 8081
# optional:
# max_no_data_retries = 10

[httpnotify]
enabled = false
on_publish = "http://localhost:3001/on_publish"
on_unpublish = "http://localhost:3001/on_unpublish"
on_play = "http://localhost:3001/on_play"
on_stop = "http://localhost:3001/on_stop"


#######################################
#   LOG configurations                #
#######################################
[log]
level = "info"
