#live server configurations
##########################
#   RTMP configurations  #
##########################
[rtmp]
enabled = true
port = 1935
# optional:
# gop_num = 0
# max_no_data_retries = 10
# read_timeout_ms = 2000

##########################
#   LOG configurations   #
##########################
[log]
level = "info"
#level = "trace"
