#live server configurations
data_dir = "./data"
#######################################
#   RTMP configurations(stand-alone)  #
#######################################
[rtmp]
enabled = true
port = 1935
# optional:
# gop_num = 0
# max_no_data_retries = 10
# read_timeout_ms = 2000

######################################
#    HLS configurations              #
######################################
[hls]
enabled = true
port = 8080
#defalut false
need_record = true
# optional:
# max_no_data_retries = 10
# no_data_sleep_ms = 100

#######################################
#   LOG configurations                #
#######################################
[log]
level = "info"
